apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-prometheus
rules:
 - apiGroups: [""]
   resources: [pods]
   verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb-prometheus
  namespace: prometheus
subjects:
 - kind: Group
   name: systemLserviceaccounts:prometheus
   apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: role-prometheus
  apiGroup: rbac.authorization.k8s.io
